server:
  port: 9988
---
management:
  server:
    port: 8988
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  cloud:
    gateway:
      routes:
        - id: EmilyFramework  # 自定义路由ID,保持唯一
          uri: lb://EmilyFramework  #目标服务地址
          order: 0 #顺序，当请求匹配到多个路由时，使用顺序小的
          predicates: # 断言，路由条件，
            - Path=/api/**